spring:
  application:
    name: consul-demo

server:
  port: 8090

com:
  alipay:
    sofa:
      rpc:
        registry:
          address: consul://127.0.0.1:8500?healthCheck.type=http&healthCheck.path=/actuator/readiness&healthCheck.port=${server.port}